# -*- coding: utf-8 -*-
namespaces=[
	"media","especial","special", u"discussió", "talk", "usuari","user", u"usuari discussió",
	"user talk", u"viquipèdia", "project", u"viquipèdia discussió", "project talk", "fitxer",
	"file", u"fitxer discussió", "file talk", "mediawiki", u"mediawiki discussió", "mediawiki talk",
	"plantilla", "template", u"plantilla discussió", "template talk", "ajuda", "help", u"ajuda discussió",
	"help talk", "categoria", "category", u"categoria discussió", "category talk", "portal",
	u"portal discussió", "viquiprojecte", u"viquiprojecte discussió", u"usuària", u"usuària discussió","image",
	"image talk", "imatge", u"imatge discussió"
]

families={
	"w" : "wikipedia",
	"wikipedia" : "wikipedia",
	"b" : "wikibooks",
	"wikibooks" : "wikibooks",
	"q" : "wikiquote",
	"wikiquote" : "wikiquote",
	"n" : "wikinews",
	"wikinews" : "wikinews",
	"s" : "wikisource",
	"wikisource" : "wikisource",
	"v" : "wikiversity",
	"wikiversity" : "wikiversity",
	"wikt" : "wiktionary",
	"wiktionary" : "wiktionary",
	#families without language
	"m" : "meta",
	"meta" : "meta",
	"metawikipedia" : "meta",
	"commons" : "commons",
	"wikispecies" : "species",
	"incubator" : "incubator",
	"wmania" : "mania",
	"wikimedia" : "foundation",
	"foundation" : "foundation",
	#unofficial
	"c": "commons",
	"wmf": "foundation",
	"mw": "mw",
	"beta": "beta",
}

projects={
	"meta" : "meta.wikimedia",
	"commons" : "commons.wikimedia",
	"species" : "species.wikimedia",
	"incubator" : "incubator.wikimedia",
	"mania" : "wikimania.wikimedia",
	"foundation" : "wikimediafoundation",
	"beta": "translatewiki",
	"mw": "www.mediawiki",
}

"""
Especial:SiteMatrix
"""

languages={
#1
"aa": u"Afar",
"ab": "Abkhazian",
"af": "Afrikaans",
"ak": "Akan",
"als": "Alemannic",
"am": "Amharik",
"an": "Aragonese",
"ang": "Anglo-Saxon",
"ar": "Arabic",
#10
"arc": "Assyrian Neo-Aramaic",
"arz": "Egyptian Arabic",
"as": "Assammese",
"ast": "Asturian",
"av": "Avar",
"ay": "Aymara",
"az": "Azeri",
"ba": "Bashkir",
"bar": "Bavarian",
"bat-smg": "Samogitian",
#20
"bcl": "Central Bicolano",
"be": "Belarusian",
"be-x-old": "Belarusian (Tarashkevitsa)",
"bg": "Bulgarian",
"bh": "Bihari",
"bi": "Bislama",
"bm": "Bambara",
"bn": "Bengali",
"bo": "Tibetan",
"bpy": "Bishnupriya Manipuri",
#30
"br": "Breton",
"bs": "Bosnian",
"bug": "Buginese",
"bxr": "Buryat (Russia)",
"ca": "Catalan",
"cbk-zam": "Zamboanga Chavacano",
"cdo": "Min Dong",
"ce": "Chechen",
"ceb": "Cebuano",
"ch": "Chamorro",
#40
"cho": "Choctaw",
"chr": "Cherokee",
"chy": "Cheyenne",
"closed-zh-tw": "",
"co": "Corsican",
"cr": "Cree",
"chr": "Crimean Tatar",
"cs": "Czech",
"csb": "Kashubian",
"cu": u"Old Church Slavonic",
#50
"cv": "Chuvash",
"cy": "Welsh",
"cz": "", # --> cs
"da": "Danish",
"de": "German",
"diq": "Zazaki",
"dk": "", #deprecated --> da
"dsb": "Lower Sorbian",
"dv": "Divehi",
"dz": "Dzongkha",
#60
"ee": "Ewe",
"el": "Greek",
"eml": "Emilian-Romagnol",
"en": "English",
"eo": "Esperanto",
"epo": "", #deprecated --> eo
"es": "Spanish",
"et": "Estonian",
"eu": "Basque",
"ext": "Extremaduran",
#70
"fa": "Persian",
"ff": "Fula",
"fi": "Finnish",
"fiu-vro": u"Võro",
"fj": "Fijian",
"fo": "Faroese",
"fr": "French",
"frp": "Franco-Provençal/Arpitan",
"fur": "Friulian",
"fy": "West Frisian",
#80
"ga": "Irish",
"gan": "Gan",
"gd": "Scotish Gaelic",
"gl": "Galician",
"glk": "Gilaki",
"gn": "Guarani",
"got": "Gothic",
"gu": "Gujarati",
"gv": "Manx",
"ha": "Hausa",
#90
"hak": "Hakka",
"haw": "Hawaiian",
"he": "Hebrew",
"hi": "Hindi",
"hif": "Fiji Hindi",
"ho": "Hiri Motu",
"hr": "Croatian",
"hsb": "Upper Sorbian",
"ht": "Haitian",
"hu": "Hungarian",
#100
"hy": "Armenian",
"hz": "Herero",
"ia": "Interlingua",
"id": "Indonesian",
"ie": "Interlingue",
"ig": "Igbo",
"ii": "Sichuan Yi",
"ik": "Inupiak",
"ilo": "Ilokano",
"io": "Ido",
#110
"is": "Icelandic",
"it": "Italian",
"iu": "Inuktitut",
"ja": "Japanese",
"jbo": "Lojban",
"jp": "", # --> ja
"jv": "Javanese",
"ka": "Georgian",
"kaa": "Karakalpak",
"kab": "Kabyle",
#120
"kg": {"*":u"kongo"},
"ki": "Kikuyu",
"kj": "Kuanyama",
"kk": "Kazakh",
"kl": "Greenlandic",
"km": "Khmer",
"kn": "Kannada",
"ko": "Korean",
"kr": "Kanuri",
"ks": "Kashmiri",
#130
"ksh": "Ripuarian",
"ku": "Kurdish",
"kv": "Komi",
"kw": "Cornish",
"ky": "Kirghiz",
"la": "Latin",
"lad": "Ladino",
"lb": "Luxemgourgish",
"lbe": "Lak",
"lg": "Luganda",
#140
"li": "Limburgian",
"lij": "Ligur",
"lmo": "Lombard",
"ln": "Lingala",
"lo": "Lao",
"lt": "Lithuanian",
"lv": "Latvian",
"map-bms": "Banyumasan",
"mdf": "Moksha",
"mg": "Magalasy",
#150
"mh": "Marshallese",
"mi": "Maori",
"minnan": "", # --> zh-min-nan
"mk": "Macedonian",
"ml": "Malayalam",
"mn": "Mongolian",
"mo": "Moldovian", # --> ru
"mr": u"maratí (मराठी)",
"ms": u"malayo (bahasa melayu)",
"mt": u"maltés (malti)",
"mus": u"muscogee",
"my": u"birmano (myanmasa)",
"na": u"fica (ekakairũ naoero)",
"nah": u"nahuatl",
"nap": u"napilitano (nnapulitano)",
"nds": u"bajo sajón (Plattdüütsch)",
"nds-nl": u"bajo sajn (Nedersaksisch)",
"ne": u"nepalés नेपाली",
"ng": u"oshiwambo",
"nl": u"holandés (nederlands)",
"nn": u"noruego (norsk (nynorsk))",
"no": u"noruego (norsk (bokmål))",
"nov": u"novial",
"nrm": u"normando (nouormand)",
"nv": u"navajo (diné bizaad)",
"ny": u"chichewa",
"oc": u"provenzal (occitan)",
"om": u"oromo (oromoo)",
"or": u"oriya (ଓଡ଼ିଆ)",
"os": u"osetio (Иронау)",
"pa": u"panyabí (ਪੰਜਾਬੀ)",
"pam": u"pampango",
"pap": u"papiamento (papiamentu)",
"pdc": u"alemán de Pensilvania (Deitsch)",
"pi": u"pali (पािऴ)",
"pih": u"norfuk / pitkern",
"pl": u"polonés (polski)",
#160
"pms": u"piemontés (piemontèis)",
"ps": u"pashto (پښتو)",
"pt": u"portugués (português)",
"qu": u"quechúa (runa simi)",
"rm": u"romanche (rumantsch)",
"rmy": u"romaní (romani)",
"rn": u"rundi (kirundi)",
"ro": u"rumano (română)",
"roa-rup": u"arumano (Armâneashti)",
"ru": u"ruso (Русский)",
#170
"rw": u"ruanda (kinyarwanda)",
"sa": u"sánscrito (संस्कृत)",
"sc": u"sardo (sardu)",
"scn": u"siciliano (sicilianu)",
"sco": u"escocés (Scots)",
"sd": u"sindhi (सिनधि)",
"se": u"sami (sámegiella)",
"sg": u"sango (sängö)",
"sh": u"serbocroata (srpskohrvatski / Српскохрватски)",
"si": u"singalés (සිංහල)",
#180
"simple": u"Simple English",
"sk": u"eslovaco (slovenčina)",
"sl": u"esloveno (Slovenščina)",
"sm": u"samoano (gagana samoa)",
"sn": u"shona (chiShona)",
"so": u"somalí (soomaaliga)",
"sq": u"albanés (shqip)",
"sr": u"serbio (Српски / Srpski)",
"ss": u"swati (siSwati)",
"st": u"sotho (seSotho)",
#190
"su": u"sunda (basa sunda)",
"sv": u"sueco (svenska)",
"sw": u"swahili (kiswahili)",
"ta": u"tamil (தமிழ்)", #tàmil
"te": u"tegulú (తెలుగు)",
"tet": u"tetun",
"tg": u"tayiko (Тоҷикӣ)",
"th": u"tailandés (ไทย)",
"ti": u"tigriña (ትግርኛ)",
"tk": u"turcomano (تركمن / Туркмен)",
#200
"tl": u"tagalo",
"tlh": u"",
"tn": u"twana (setswana)",
"to": u"tongano (faka-Tonga)", #tongalés
"tokipona": u"toki pona",
"tpi": u"tok pisin",
"tr": u"turco (türkçe)",
"ts": u"tonga (xitsonga)",
"tt": u"t¡rtaro (Tatarça)", #tàtar
"tum": u"tumbuka (chiTumbuka)",
#210
"tw": u"twi",
"ty": u"tahitiano (reo mā`ohi)",
"udm": u"votiaco (Удмурт)",
"ug": u"uigur (oyghurque)",
"uk": u"ucraniano (Українська)",
"ur": u"urdú (اردو)",
"uz": u"uzbeko (Ўзбек)",
"ve": u"venda (tshivenda)",
"vec": u"venciano (vèneto)",
"vi": u"vietnamita (Tiếng Việt)",
#220
"vls": u"flamenco occidental (west-vlaoms)",
"vo": u"volapük",
"wa": u"walon",
"war": u"waray (Samar-Leyte Visayan)",
"wo": u"wollof",
"xal": u"calmuco (Хальмг)",
"xh": u"xhosa (isiXhosa)",
"yi": u"yídis ייִדיש",
"yo": u"yoruba (yorùbá)",
"za": u"Zuangh",
#230
"zh": u"chino (中文)",
"zh-min-nan": u"min del sur (bân-lâm-gú)",
"zh-yue": u"cantonés (粵語)",
"zu": u"zulú (isiZulu)",
}
