#! /usr/bin/env python
# -*- coding: utf-8 -*-

"""
games.py
"""

import random, re
#import browser

def f_random(self, origin, args): 
   """.random <experssion> - ."""
   params =args.params
   result = ""
   if params:
      b=[]
      if ", " in params:
         b=params.split(", ")
      elif "," in params:
         b=params.split(",")
      if len(b)==2 and b[0].isdigit() and b[1].isdigit():
         #random numbers are generated by decimal number, obviously a @ran 0,1 always gets 1
         #add 1 always and later substract it
         b=[int(b[0])+1,int(b[1])+1]
         if b[0]>b[1]:
            b=[b[1],b[0]]
         b=random.randint(b[0],b[1])-1
         result = str(b)
      elif len(b)>1:
         choice=random.choice(b)
         result=choice.encode("utf-8")
      else:
         result="el número de opciones es insuficiente."
   else:
      b=random.randint(1,2)
      if b==1:
         result="nones"
      else:
         result="pares"
   if result:
      self.msg(origin.target,result)
f_random.rule = ['ran','random']
f_random.showas = "ran(dom)"

def f_joke(self, origin, args): 
   """.chiste - envía algo gracioso, se supone."""
   import os, codecs
   jokedir = os.path.join(os.getcwd().replace("/modules",""), 'chistes')
   fs =["chikito","chistes","colmos","definiciones","feministas",
        "habia","jaimito","mama","tags","verdes"]
   f = random.choice(fs)
   f += ".txt"
   f = open(jokedir+"/"+f,"r")
   f=f.read()
   lines=f.splitlines()
   joke=random.choice(lines)
   self.msg(origin.target, joke)
f_joke.rule = ['chiste','joke']
f_joke.showas = "chiste|joke"
   
def f_quote(self, origin, args): 
   """.dialgo - algo hará..."""
   import os, codecs
   jokedir = os.path.join(os.getcwd().replace("/modules",""), 'chistes')
   fs =os.listdir(jokedir)
   f = random.choice(fs)
   f = open(jokedir+"/"+f,"r")
   f=f.read()
   lines=f.splitlines()
   joke=random.choice(lines)
   self.msg(origin.target, joke)
f_quote.rule = ['quote','dialgo']
f_quote.showas = "quote|dialgo"
   

def f_selquote(self, origin, args): 
   """.selquote <citas|chistes|filosofia|discri|estupido|piropos|refranes>"""
   matrix={"citas":["citas"],
           "chistes":["chikito","chistes","colmos","definiciones",
                      "feministas","habia","jaimito"
                      "mama","tags","verdes","win95"],
           "filosofia": ["filosofa"],
           "discri":["gallegos","Lepe","rubias","si_ella"],
           "estupido": ["estupido","Tonto","tumadre"],
           "piropos":["piropos"],
           "refranes":["refranero"]
           }
   import os, codecs
   jokedir = os.path.join(os.getcwd().replace("/modules",""), 'chistes')
   choosen = args.params

   if choosen in [u"filosofía","filosofa"]: choosen= "filosofia"
   elif choosen in ["cita", "quote"]: choosen = "citas"
   elif choosen=="chiste": choosen = "chistes"
   elif choosen in ["refran","refranero",u"refrán"]: choosen = "refranes"
   elif choosen in ["piropo"]: choosen = "piropos"
   elif choosen in ["dicriminatorio"]: choosen = "discri"
   
   if choosen not in matrix: choosen = random.choice(matrix.keys())
   
   f = random.choice(matrix[choosen])
   f += ".txt"
   f = open(jokedir+"/"+f,"r")
   f=f.read()
   lines=f.splitlines()
   joke=random.choice(lines)
   self.msg(origin.target, joke)
f_selquote.rule = 'selquote'
f_selquote.showas = "selquote"
   

if __name__ == "__main__":
   import os, codecs
   jokedir = os.path.join(os.getcwd().replace("/modules",""), 'chistes')
   files =os.listdir(jokedir)
   filename = random.choice(files)
   filename = open(jokedir+"/"+f,"r")
   filetxt=f.read()
   lines=filtxt.splitlines()
   joke=random.choice(lines)
   print "%s:\n" % filename, joke

